#!/bin/sh

apt-get -y update && apt-get -y upgrade;
apt-get -y install git;
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -;
sudo apt-get install -y nodejs;
git clone https://github.com/BeneCollyridam/movienight.git;
cd movienight;
npm install;
npm start;
